import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window]
dynamic_title = true
opacity = 1.0

[window.padding]
x = 10
y = 8
