{
    imports = [
        ./alacritty
        ./anki
        ./blocky
        ./btop
        ./bundles
        ./discord
        ./docker
        ./firefox
        ./fish
        ./git
        ./hardware
        ./nautilus
        ./neovim
        ./plex
        ./plymouth
        ./rofi
        ./stylix
        ./tmux
        ./virt-manager
    ];
}
