creation_rules:
  - key_groups:
      - age:
          - age1v4858p85k29tp0rg9phvvaa4gyx07mdgvlumud52mhmyhrmfcaxsyckzd0 # desktop
          - age14hmv66c09cf0qfh7vz28nyqp6vnx775hsus6e3tw294tpem45qrsgdt2dm # ds1
          - age1hhl2mn3wnnwav3gu5ngn25h9jljq3y0eu77vuvgwkel57jxu0vfq4nushv # workstation
          - age1esy7fmulzy3sf7a2wea552e6242fqt6uu0hm7wtg7nu08jx0yyfscqx6w9 # nix-pi
